apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc  #we will mention in the pvc yml file
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp3