apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zomato-daemon
  labels:
    app: zomato
spec:
  selector:
    matchLabels:
      name: zomato
  template:
    metadata:
      labels:
        name: zomato
    spec: 
      containers:
        - name: zomato-container
          image: kastrov/zomato
          ports: 
            - containerPort: 3000