apiVersion: v1
kind: Namespace
metadata:
  name: swiggy-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: swiggy-pod
  namespace: swiggy-ns
  labels:
    app: swiggy
spec:
  containers:
    - name: swiggy-container
      image: kastrov/swiggy
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
  namespace: swiggy-ns
spec:
  type: NodePort
  selector:
    app: swiggy
  ports:
    - port: 3000
      targetPort: 3000 #container port
      
