apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zomato-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato-app
  template:
    metadata:
      name: zomato-pod
      labels:
        app: zomato-app
    spec:
      containers:
        - name: zomato-container
          image: kastrov/zomato
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: NodePort
  selector:
    app: zomato-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
